"""
Train anemia CV model on synthetic conjunctival data, export to ONNX.

HONEST DOCUMENTATION:
- Dataset: SYNTHETIC images generated by generate_synthetic_anemia.py
- 320 train + 80 val + 100 test
- Not validated on real Indonesian patient data
- Use as baseline; replace with HemaVision fine-tuning for production

Output:
    ai-service/app/model_artifacts/anemia_mobilenetv3_v1.onnx
    ai-service/app/model_artifacts/anemia_mobilenetv3_v1_metadata.json
"""
import os
import json
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset
from PIL import Image
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

DATASET_DIR = "/Users/zelphyx/Projects/Maternin-AI/datasets/anemia_synthetic"
ARTIFACT_DIR = "/Users/zelphyx/Projects/Maternin-AI/ai-service/app/model_artifacts"
ONNX_PATH = os.path.join(ARTIFACT_DIR, "anemia_mobilenetv3_v1.onnx")
META_PATH = os.path.join(ARTIFACT_DIR, "anemia_mobilenetv3_v1_metadata.json")
SEED = 42


def load_split(split: str):
    images, labels = [], []
    for label_name, label_val in [("normal", 0), ("anemia", 1)]:
        folder = os.path.join(DATASET_DIR, split, label_name)
        for fname in sorted(os.listdir(folder)):
            if not fname.endswith(".jpg"):
                continue
            img = Image.open(os.path.join(folder, fname)).convert("RGB").resize((224, 224))
            arr = np.array(img, dtype=np.float32) / 255.0
            mean = np.array([0.485, 0.456, 0.406])
            std = np.array([0.229, 0.224, 0.225])
            arr = (arr - mean) / std
            images.append(arr)
            labels.append(label_val)
    return np.array(images), np.array(labels)


class SmallAnemiaCNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 16, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm2d(16)
        self.pool1 = nn.MaxPool2d(2)
        self.conv2 = nn.Conv2d(16, 32, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm2d(32)
        self.pool2 = nn.MaxPool2d(2)
        self.conv3 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.bn3 = nn.BatchNorm2d(64)
        self.pool3 = nn.MaxPool2d(2)
        self.fc1 = nn.Linear(64 * 28 * 28, 64)
        self.fc2 = nn.Linear(64, 2)
        self.dropout = nn.Dropout(0.3)

    def forward(self, x):
        x = self.pool1(F.relu(self.bn1(self.conv1(x))))
        x = self.pool2(F.relu(self.bn2(self.conv2(x))))
        x = self.pool3(F.relu(self.bn3(self.conv3(x))))
        x = x.flatten(1)
        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.fc2(x)
        return x


def main():
    torch.manual_seed(SEED)
    np.random.seed(SEED)

    print("=" * 70)
    print("Anemia CV Training (PyTorch -> ONNX)")
    print("=" * 70)

    print("\n[1/4] Loading dataset...")
    X_train_full, y_train_full = load_split("train")
    X_test, y_test = load_split("test")
    X_train_full = np.transpose(X_train_full, (0, 3, 1, 2))
    X_test = np.transpose(X_test, (0, 3, 1, 2))
    print(f"  Train pool: {X_train_full.shape}, labels: {np.bincount(y_train_full)}")
    print(f"  Test:       {X_test.shape}, labels: {np.bincount(y_test)}")

    n = len(X_train_full)
    val_size = int(n * 0.2)
    rng = np.random.RandomState(SEED)
    idx = rng.permutation(n)
    val_idx, train_idx = idx[:val_size], idx[val_size:]
    X_train, y_train = X_train_full[train_idx], y_train_full[train_idx]
    X_val, y_val = X_train_full[val_idx], y_train_full[val_idx]
    print(f"  After split: train={len(X_train)}, val={len(X_val)}, test={len(X_test)}")

    X_train_t = torch.tensor(X_train, dtype=torch.float32)
    y_train_t = torch.tensor(y_train, dtype=torch.long)
    X_val_t = torch.tensor(X_val, dtype=torch.float32)
    y_val_t = torch.tensor(y_val, dtype=torch.long)
    X_test_t = torch.tensor(X_test, dtype=torch.float32)
    y_test_t = torch.tensor(y_test, dtype=torch.long)

    train_loader = DataLoader(TensorDataset(X_train_t, y_train_t), batch_size=32, shuffle=True)

    print(f"\n[2/4] Building model...")
    model = SmallAnemiaCNN()
    n_params = sum(p.numel() for p in model.parameters())
    print(f"  SmallAnemiaCNN: {n_params:,} parameters")

    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)
    criterion = nn.CrossEntropyLoss()

    print(f"\n[3/4] Training for 20 epochs...")
    best_val_acc = 0.0
    best_state = None
    train_accs, val_accs = [], []
    for epoch in range(20):
        model.train()
        total_loss = 0.0
        for X_batch, y_batch in train_loader:
            optimizer.zero_grad()
            logits = model(X_batch)
            loss = criterion(logits, y_batch)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()

        model.eval()
        with torch.no_grad():
            train_preds = model(X_train_t).argmax(dim=1).numpy()
            val_preds = model(X_val_t).argmax(dim=1).numpy()
        train_acc = float((train_preds == y_train).mean())
        val_acc = float((val_preds == y_val).mean())
        train_accs.append(train_acc)
        val_accs.append(val_acc)
        print(f"  Epoch {epoch+1:2d}/20 | Loss: {total_loss/len(train_loader):.4f} | "
              f"Train Acc: {train_acc:.4f} | Val Acc: {val_acc:.4f}")
        if val_acc > best_val_acc:
            best_val_acc = val_acc
            best_state = {k: v.clone() for k, v in model.state_dict().items()}

    model.load_state_dict(best_state)

    print(f"\n[4/4] Final evaluation on held-out test set...")
    model.eval()
    with torch.no_grad():
        test_logits = model(X_test_t)
        test_probs = F.softmax(test_logits, dim=1)[:, 1].numpy()
        test_preds = test_logits.argmax(dim=1).numpy()

    acc = accuracy_score(y_test, test_preds)
    prec = precision_score(y_test, test_preds, zero_division=0)
    rec = recall_score(y_test, test_preds, zero_division=0)
    f1 = f1_score(y_test, test_preds, zero_division=0)
    cm = confusion_matrix(y_test, test_preds)

    print(f"  Accuracy:  {acc:.4f} ({acc:.2%})")
    print(f"  Precision: {prec:.4f}")
    print(f"  Recall:    {rec:.4f}")
    print(f"  F1-Score:  {f1:.4f}")
    print(f"  Confusion Matrix:")
    print(f"    TN={cm[0][0]}  FP={cm[0][1]}")
    print(f"    FN={cm[1][0]}  TP={cm[1][1]}")

    final_train_acc = train_accs[-1]
    final_val_acc = val_accs[-1]
    overfit_gap = final_train_acc - final_val_acc
    print(f"\n  Overfitting Diagnostic:")
    print(f"    Final Train Acc: {final_train_acc:.4f}")
    print(f"    Final Val Acc:   {final_val_acc:.4f}")
    print(f"    Gap: {overfit_gap:.4f} ({overfit_gap*100:.2f} pp)")
    if overfit_gap > 0.10:
        print(f"    WARNING: Gap > 10pp suggests some overfitting")
    else:
        print(f"    OK: Gap < 10pp, model generalizes")

    print(f"\n[5/5] Exporting to ONNX...")
    os.makedirs(ARTIFACT_DIR, exist_ok=True)
    model.eval()
    dummy_input = torch.randn(1, 3, 224, 224)
    torch.onnx.export(
        model, dummy_input, ONNX_PATH,
        input_names=["input"],
        output_names=["logits"],
        dynamic_axes={"input": {0: "batch"}, "logits": {0: "batch"}},
        opset_version=13,
    )
    print(f"  ONNX saved: {ONNX_PATH} ({os.path.getsize(ONNX_PATH):,} bytes)")

    metadata = {
        "model_name": "anemia_mobilenetv3_v1",
        "model_type": "SmallCNN (3 conv layers + 2 FC)",
        "n_parameters": n_params,
        "dataset": "synthetic_conjunctival_pallor",
        "dataset_size_train": len(X_train),
        "dataset_size_val": len(X_val),
        "dataset_size_test": len(X_test),
        "epochs": 20,
        "input_shape": [1, 3, 224, 224],
        "classes": ["normal", "anemia"],
        "format": "ONNX",
        "metrics": {
            "train_accuracy": round(float(final_train_acc), 4),
            "val_accuracy": round(float(final_val_acc), 4),
            "test_accuracy": round(float(acc), 4),
            "test_precision": round(float(prec), 4),
            "test_recall": round(float(rec), 4),
            "test_f1": round(float(f1), 4),
            "overfit_gap": round(float(overfit_gap), 4),
        },
        "confusion_matrix": {
            "TN": int(cm[0][0]), "FP": int(cm[0][1]),
            "FN": int(cm[1][0]), "TP": int(cm[1][1]),
        },
        "warning": "Trained on SYNTHETIC images. Not validated on real Indonesian patient data. Replace with HemaVision fine-tuning for production.",
    }
    with open(META_PATH, "w") as f:
        json.dump(metadata, f, indent=2)

    print(f"\n  Metadata saved: {META_PATH}")
    print(f"\n{'=' * 70}")
    print(f"OK Anemia CV Training Complete!")
    print(f"{'=' * 70}")


if __name__ == "__main__":
    main()
